"""add model_catalog and gpu_pricing tables

Revision ID: 5d716f49b7ac
Revises: c631a2aed670
Create Date: 2026-06-18 21:14:10.365590

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d716f49b7ac"
down_revision: str | None = "c631a2aed670"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gpu_pricing",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("vendor", sa.String(length=50), nullable=False),
        sa.Column("gpu_type", sa.String(length=100), nullable=False),
        sa.Column("vram_gb", sa.Integer(), nullable=False),
        sa.Column("price_per_hour_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_gpu_pricing_vendor_gpu_type", "gpu_pricing", ["vendor", "gpu_type"], unique=True
    )
    op.create_table(
        "model_catalog",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("family", sa.String(length=100), nullable=False),
        sa.Column("parameter_count_b", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("supports_instruct", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_catalog_model_id"), "model_catalog", ["model_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_catalog_model_id"), table_name="model_catalog")
    op.drop_table("model_catalog")
    op.drop_index("idx_gpu_pricing_vendor_gpu_type", table_name="gpu_pricing")
    op.drop_table("gpu_pricing")
    # ### end Alembic commands ###
